export const LOAD_DATA_INIT = 'LOAD_DATA_INIT';
export const LOAD_MORE_DATA_INIT = 'LOAD_MORE_DATA_INIT';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILED = 'SEARCH_USER_FAILED';
